config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'user/:id/invite' => 'user#invite' , :as => 'invie_user'

   root 'home#index'

    resources :invites
    resources :profiles
    post '/search' => "profiles#search" , :as=>"search_user"
    get '/show_profile' => "home#show_profile" , :as => "show_profile"
    get '/user/:user_id/user_profile' => "home#user_profile"

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :profile
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile
end

app/models/invite.rb
class Invite < ActiveRecord::Base
	 belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :skills
  has_many :educations
  has_many :companys
  belongs_to :user
	accepts_nested_attributes_for :skills, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :educations, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :companys, :reject_if => :all_blank, :allow_destroy => true
  
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  

has_attached_file :image
validates_attachment :image, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :profile
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :invites
	has_one :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_filter :authenticate_user!

  def after_sign_out_path_for(user)
    new_user_session_path 
  end

  def after_sign_in_path_for(user)
    unless current_user.profile.present?
      new_profile_path
    else
  	 root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
  def show_profile
  	@profile = Profile.new
  end

  def user_profile
  	@user = User.find(params[:user_id])
  	@profile = @user.profile
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
   before_action :status
  def new
  	@invite = Invite.new
  end

  def create
     if @user = User.find_by_email(params[:invite][:email])
    	   redirect_to new_invite_path ,	notice: 'This Email already Registerd.'
       else
         @invite = current_user.invites.build(invite_params)
	  	   @invite.save
	  	   UserMailer.invite_email(@invite).deliver_later
	  	  redirect_to root_path , notice: 'Invitation  successfully Sended.'
      end
  end

  private

  def invite_params
      params.require(:invite).permit(:email, :user_id)
    end
  def status
    (redirect_to root_path, alert: 'unauthorised access') unless current_user.is_admin.present?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	
  def search
    @q = Profile.ransack(params[:q])
    @profiles = @q.result
  end

  def show
    @profile = Profile.find(params[:id])
    @skill = @profile.skills

  end

	def new
		@profile = Profile.new
    @skill = Skill.new
    @education = Education.new
    @company = Company.new
  end

  def edit
    @profile = current_user.profile
    @skill = @profile.skills
    @company = @profile.companys
    @education = @profile.educations
  end
 
  def create
    @profile = current_user.build_profile(profile_params)
   if @profile.save
      redirect_to root_path,  notice: 'Profile Successfully create .'
     else
       render 'new' 
    end
  end

  def update
       @profile = Profile.find_by_user_id(params[:id])
   if  @profile.update(profile_params)
       redirect_to root_path
      else
       render 'edit'
    end
 end

  private

  def profile_params
    params.require(:profile).permit(:username, :mobile, :dob, :gender, :address, :city, :education, :skill, :company_name, :experience, :user_id, :image, skills_attributes: [:id, :name], companys_attributes: [:id, :name], educations_attributes: [:id, :name])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/_show_user_profile.html.erb
<p>
  <%= image_tag profile.image.url(:medium) %>
</p>

<p>
  <strong>User Name:</strong>
  <%= profile.username %>
</p>
 
<p>
  <strong>Molibe No.:</strong>
  <%= profile.mobile %>
</p>
<p>
  <strong>Address.:</strong>
  <%= profile.address %>
</p>
<p>
  <strong>Gender:</strong>
  <%= profile.gender %>
</p>

<p>
  <strong>Company:</strong>
  <%= profile.company_name %>
</p>
<!-- <p>
  <strong>education:</strong>
  <%= profile.education %>
</p> -->

<!-- <p>
  <strong>Experience:</strong>
  <%= profile.experience %>
</p> -->

<!-- <p>
  <strong>Company Name:</strong>
  <%= profile. company_name %>
</p>
 -->
<%#= link_to 'Back', home_index_path %>

app/views/home/index.html.erb
</br>
<% if current_user.is_admin == true  %>
  <h4> Admin </h4>
  <h3> Search User </h3>
 <%= search_form_for Profile.ransack(params[:q]), url: search_user_path, method: :post do |f| %>
       
    <%= f.search_field :username_or_skill_or_education_or_company_name_or_experience_or_address_cont %>
    <%= f.submit "Search" %>
  <% end %>
<% end %>

   <!-- <h3> Invited User List </h3>
   <% Invite.all.each do |invite| %>
    <%= invite.email%>
   <% end %> -->

   <!-- <table> 
      <h2> All User List </h2>
     <% User.all.each do |user| %>
        <% unless user.email == current_user.email %>
            <tr>
              <td> <%= user.email %></br></td>
            </tr>
          <% end %>
       <% end %>
    </table>
 <% else %>
	<%= current_user.email%>
 -->

app/views/home/show_profile.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<%= form_for @profile , url: show_profile_path, :remote=>true do |f| %>

  <p>
    <%= f.label :user %><br>
    <%= f.select :user_id,User.all.map{|c| [c.email ,c.id]} %>
  </p>
  <p>
   <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= image_tag @profile.image.url(:medium) if @profile.image.present? %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :mobile %><br>
    <%= f.number_field :mobile %>
  </p>

  <p>
    <%= f.label :dob %><br>
    <%= f.date_field :dob %>
  </p>

  <p id = 'gender'>
    <%= f.label :gender %><br />
    <%= f.radio_button :gender, "M", :checked=>true %>male
    <%= f.radio_button :gender, "F" %>female
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  
  <p>
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </p>


  <p>
    <%= f.submit "Create Profile" %>
  </p>
<% end %>

	<script >
		$(document).ready(function(){
	    $('#profile_user_id').change(function(){
	      $.get("/user/"+$("#profile_user_id").val()+"/user_profile");
	    })
		});
	</script>

app/views/home/user_profile.js.erb
$("#profile_username").val("<%= @profile.username%>");
$("#profile_mobile").val("<%= @profile.mobile%>");
$("#profile_dob").val("<%= @profile.dob%>");
$("#profile_address").val("<%= @profile.address%>");
$("#profile_city").val("<%= @profile.city%>");
$("#profile_experience").val("<%= @profile.experience%>");
$("#profile_image").val("<%= @profile.image%>"); 

app/views/invites/new.html.erb
<% if current_user.is_admin?%>
<h3>Send a Invitation </h3> 
  <%= form_for @invite , url: invites_path, :id => "new_user" do |f| %>
   <table>
    <tr>
       <td> <%= f.label :email %>
       <%= f.email_field :email %></td>
       <td><%= f.submit "Invite", :id => "user_submit" %></td>
    </tr>
   </table>
   <% end %>
  <%= link_to 'Back', home_index_path %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%#= javascript_include_tag :cocoon %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Blog</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <%# if current_user.is_admin == true %>
            <li><%#= link_to "Invite", new_invite_path  %></li>
            <li><%#= link_to "Logout", destroy_user_session_path , method: :delete  %>
            <li><%#= link_to "Link2", "/path2"  %></li>

            <% if user_signed_in? %>
              <% if current_user.is_admin == true %>
                <li><%= link_to "Invite", new_invite_path  %></li>
                 <li><%= link_to "Show User Profile", show_profile_path  %></li>
                
              <% end %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
              <% unless current_user.is_admin? %>
                <% if current_user.profile.present? %>
                  <li><%= link_to "View Profile", profile_path(current_user.profile) %></li>
                  <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                <%end%>
                <% if  !current_user.profile.present?%>
                  <li><%= link_to "Create Profile", new_profile_path %></li>
                <%end%>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/profiles/_company_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :company %>
    <br/>
    <%= f.text_field :name %>
  </div>
  <%= link_to_remove_association "remove company", f %>
</div>

app/views/profiles/_education_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :education %>
    <br/>
    <%= f.text_field :name %>
  </div>
  <%= link_to_remove_association "remove education", f %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>

  <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@profile.errors.count, "error") %> prohibited
          this Registration from being saved:
        </h2>
        <ul>
          <% @profile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= link_to 'Back', home_index_path %>

  <p>
   <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= image_tag @profile.image.url(:medium) %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :mobile %><br>
    <%= f.number_field :mobile %>
  </p>

  <p>
    <%= f.label :dob %><br>
    <%= f.date_field :dob %>
  </p>

  <p>
    <%= f.label :gender %><br />
    <%= f.radio_button :gender, "M", :checked=>true %>male
    <%= f.radio_button :gender, "F" %>female
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>



  <div id="skills">
    <%= f.fields_for :skills, @skill do |task| %>
      <%= render 'skill_fields', :f => task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add skill', f, :skills %>
    </div>
  </div>
<br>
  <div id="educations">
    <%= f.fields_for :educations,@education do |education| %>
      <%= render 'education_fields', :f => education %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add education', f, :educations %>
    </div>
  </div>
<br>

  <div id="company">
    <%= f.fields_for :companys,@company do |company| %>
      <%= render 'company_fields', :f => company %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add company', f, :companys %>
    </div>
  </div>

<br>

  
  <p>
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </p>


  <p>
    <%= f.submit "Create Profile" %>
  </p>
<% end %>

app/views/profiles/_skill_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :Skill %>
    <br/>
    <%= f.text_field :name %>
  </div>
  <%= link_to_remove_association "remove skill", f %>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
 
<%= render partial: 'form'  %>
 
<%= link_to 'Back', root_path %>

app/views/profiles/new.html.erb
<%= render partial: 'form'  %>
<%= link_to 'Back', root_path %>

app/views/profiles/search.html.erb
<h3> Result</h3>
<% @profiles.each do |profile| %>
<%= link_to (image_tag profile.image.url(:thumb)), profile_path(profile) %>
<%= link_to profile.username, profile_path(profile) %></br>
<% end %>
<%= link_to 'Back', home_index_path %>

app/views/profiles/show.html.erb
<p>
  <%= image_tag @profile.image.url(:medium) %>
</p>

<p>
  <strong>User Name:</strong>
  <%= @profile.username %>
</p>
 
<p>
  <strong>Molibe No.:</strong>
  <%= @profile.mobile %>
</p>
<p>
  <strong>Address.:</strong>
  <%= @profile.address %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>
<p>
  <strong>Skill:</strong>
  <%= @skill.name %>
</p>
<p>
  <strong>Company:</strong>
  <%= @profile.company_name %>
</p>
<p>
  <strong>education:</strong>
  <%= @profile.education %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @profile.experience %>
</p>

<p>
  <strong>Company Name:</strong>
  <%= @profile. company_name %>
</p>

<%= link_to 'Back', home_index_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>